apiVersion: v1
entries:
  gpu-operator:
  - apiVersion: v2
    appVersion: v1.10.0
    created: "2022-01-03T21:27:18.976578-08:00"
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: b84e2648e47af4da17cad565a6419a25ddd7bf5f79280bb3ff3d6fc77a0ce059
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - file:///charts/gpu-operator/gpu-operator-v1.10.0.tgz
    version: v1.10.0
generated: "2022-01-03T21:27:18.974241-08:00"
