apiVersion: v1
entries:
  gpu-operator:
  - apiVersion: v2
    appVersion: v1.10.0
    created: "2021-12-14T12:52:37.143869-08:00"
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: 24c8b4b4cfe41d5544909e5b9bfddd631388326511f816928fbcb7a8bb33cceb
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - file:///charts/gpu-operator/gpu-operator-v1.10.0.tgz
    version: v1.10.0
generated: "2021-12-14T12:52:37.141378-08:00"
