{{- if .Values.driver.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nvidia-driver
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - 'create'
  - 'delete'
  - 'update'
  - 'patch'
  - 'get'
  - 'list'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - 'create'
  - 'delete'
  - 'update'
  - 'patch'
  - 'get'
  - 'list'
{{- end }}
