{{- if .Values.toolkit.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-container-toolkit
  namespace: {{.Values.specialresource.spec.namespace}}
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - gpu-operator-privileged
{{- end }}
