apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nvidia-operator-validator
  namespace: {{.Values.specialresource.spec.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nvidia-operator-validator
subjects:
- kind: ServiceAccount
  name: nvidia-operator-validator
  namespace: {{.Values.specialresource.spec.namespace}}
