{{- if .Values.devicePlugin.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nvidia-device-plugin-daemonset
  name: nvidia-device-plugin-daemonset
  namespace: {{.Values.specialresource.spec.namespace}}
  annotations:
    openshift.io/scc: hostmount-anyuid
spec:
  selector:
    matchLabels:
      app: nvidia-device-plugin-daemonset
  template:
    metadata:
      labels:
        app: nvidia-device-plugin-daemonset
    spec:
      {{- if eq .Values.containerRuntime "containerd" }}
      runtimeClassName: {{.Values.runtimeClass | default "nvidia" }}
      {{- end }}
      nodeSelector:
        nvidia.com/gpu.deploy.device-plugin: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      priorityClassName: system-node-critical
      serviceAccount: nvidia-device-plugin
      initContainers:
      - name: toolkit-validation
        image: {{ include "image.fullname" .Values.validator }}
        command: ['sh', '-c']
        args: ["until [ -f /run/nvidia/validations/toolkit-ready ]; do echo waiting for nvidia container stack to be setup; sleep 5; done"]
        securityContext:
          privileged: true
        volumeMounts:
          - name: run-nvidia
            mountPath: /run/nvidia
            mountPropagation: HostToContainer
      containers:
      - image: {{ include "image.fullname" .Values.devicePlugin }}
        name: nvidia-device-plugin-ctr
        securityContext:
          privileged: true
        env:
          - name: MIG_STRATEGY
            value: {{.Values.mig.strategy}}
          {{- range .Values.devicePlugin.env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: run-nvidia
          hostPath:
            path: "/run/nvidia"
            type: Directory
{{- end }}
