{{- if .Values.dcgm.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nvidia-dcgm
  namespace: {{.Values.specialresource.spec.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nvidia-dcgm
subjects:
- kind: ServiceAccount
  name: nvidia-dcgm
  namespace: {{.Values.specialresource.spec.namespace}}
{{- end }}
