{{- if .Values.dcgmExporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-dcgm-exporter
  namespace: {{.Values.specialresource.spec.namespace}}
  labels:
    app: nvidia-dcgm-exporter
spec:
  endpoints:
  - port: gpu-metrics
    path: "/metrics"
  jobLabel: app
  namespaceSelector:
    matchNames:
    - {{.Values.specialresource.spec.namespace}}
  selector:
    matchLabels:
     app: nvidia-dcgm-exporter
{{- end }}
