{{- if .Values.gfd.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nvidia-gpu-feature-discovery
  namespace: {{.Values.specialresource.spec.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nvidia-gpu-feature-discovery
subjects:
- kind: ServiceAccount
  name: nvidia-gpu-feature-discovery
  namespace: {{.Values.specialresource.spec.namespace}}
{{- end }}
