{{- if .Values.migManager.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-mig-manager
  namespace: {{.Values.specialresource.spec.namespace}}
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - 'create'
  - 'delete'
  - 'update'
  - 'patch'
  - 'get'
  - 'list'
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - gpu-operator-privileged
{{- end }}
