{{- if .Values.migManager.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nvidia-mig-manager
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - 'create'
  - 'delete'
  - 'update'
  - 'patch'
  - 'get'
  - 'list'
{{- end }}
