apiVersion: v1
entries:
  driver-container-base:
  - annotations:
      appVersion: '>= 1.13.0 < 1.15.0'
    apiVersion: v2
    appVersion: 1.0.0
    created: "2021-12-14T12:52:36.774618-08:00"
    description: Driver Container Base is the base image for out-of-tree builds
    digest: a839909c4fe03451dcca76c6be3f60e3922994ce2ed521ad51f155a040684cb5
    icon: https://avatars.githubusercontent.com/u/55542927
    name: driver-container-base
    type: application
    urls:
    - file:///charts/deprecated/driver-container-base-0.1.0.tgz
    version: 0.1.0
generated: "2021-12-14T12:52:36.773909-08:00"
