apiVersion: v2
name: gpu-operator
version: v1.10.0
kubeVersion: ">= 1.16.0-0"
description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
appVersion: "v1.10.0"
icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
sources:
- https://github.com/NVIDIA/gpu-operator
home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
keywords:
  - gpu
  - cuda
  - compute
  - operator
  - deep learning
  - monitoring
  - tesla
